Algoritmo "Tabela Verdade"

Var
// Seção de Declarações das variáveis 

i, j : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 10
j <- 20

  // sim E nao = Nao
  // sim E sim = sim
  // nao E nao = Nao
  // sim OU nao = sim
  // sim OU sim = sim
  // nao OU nao = Nao

se (i = 10) OU  (j = 20) entao
   Escreval("Fazer algo")
senao
     Escreval ("Nao fazer nada")
fimse


Fimalgoritmo